using System.Linq;
using BTD_Mod_Helper.Api.Data;
using BTD_Mod_Helper.Api.Enums;
using BTD_Mod_Helper.Extensions;
using HarmonyLib;
using Il2CppAssets.Scripts.Models;
using Il2CppAssets.Scripts.Models.Towers.Behaviors.Abilities.Behaviors;
using Il2CppAssets.Scripts.Models.Towers.Projectiles.Behaviors;
using Il2CppAssets.Scripts.Models.TowerSets;
using Il2CppAssets.Scripts.Simulation.Towers;
using Il2CppAssets.Scripts.Simulation.Towers.Behaviors;

namespace TacticalTweaks.Tweaks;

public class BetterCentralMarket : ToggleableTweak
{
    protected override bool DefaultEnabled => false;

    public override string Description =>
        "Makes the Central Market buff affect all non-Support towers' income generation not just Merchantmen.";

    protected override string Icon => VanillaSprites.CentralMarketUpgradeIcon;

    [HarmonyPatch(typeof(CentralMarketBuff), nameof(CentralMarketBuff.TestTower))]
    internal static class CentralMarketBuff_TestTower
    {
        [HarmonyPrefix]
        internal static bool Prefix(CentralMarketBuff __instance, Tower testTower)
        {
            if (!GetInstance<BetterCentralMarket>().Enabled) return true;

            if (testTower == __instance.tower ||
                !testTower.towerModel.Is(out var towerModel) ||
                towerModel.CheckSet(TowerSet.Support, false))
                return false;

            testTower.RemoveMutatorIncludeSubTowers(__instance.mutator);
            testTower.AddMutatorIncludeSubTowers(__instance.mutator);

            return false;
        }
    }

    [HarmonyPatch(typeof(CentralMarketBuff), nameof(CentralMarketBuff.Attatched))]
    internal static class CentralMarketBuff_Attatched
    {
        [HarmonyPrefix]
        internal static void Prefix(CentralMarketBuff __instance)
        {
            if (!GetInstance<BetterCentralMarket>().Enabled) return;

            foreach (var tower in __instance.Sim.factory.GetRaw<Tower>().list)
            {
                __instance.TestTower(tower, __instance.tower.towerModel, 0, 0);
            }
        }
    }

    [HarmonyPatch(typeof(CentralMarketBuff.CentralMarketMutator), nameof(CentralMarketBuff.CentralMarketMutator.Mutate))]
    internal static class CentralMarketMutator_CentralMarketMutator
    {
        [HarmonyPostfix]
        internal static void Postfix(CentralMarketBuff __instance, Model model, ref bool __result)
        {
            if (!GetInstance<BetterCentralMarket>().Enabled) return;

            var multiplier = __instance.centralMarketBuffModel.multiplier;
            var bonus = multiplier - 1f;

            foreach (var cash in model.GetDescendants<CashModel>().AsIEnumerable())
            {
                cash.bonusMultiplier += bonus;
                __result = true;
            }

            foreach (var cashPerFarm in model.GetDescendants<CashPerBananaFarmInRangeModel>().AsIEnumerable())
            {
                cashPerFarm.baseCash *= multiplier;
                cashPerFarm.cash *= multiplier;
                __result = true;
            }

            foreach (var increaseBloonWorth in model.GetDescendants<IncreaseBloonWorthModel>().AsIEnumerable())
            {
                if (increaseBloonWorth.cash > 0)
                {
                    increaseBloonWorth.cash *= multiplier;
                }
                else
                {
                    increaseBloonWorth.cashMultiplier *= multiplier;
                }
                __result = true;
            }

            foreach (var moabTakedown in model.GetDescendants<MoabTakedownModel>().AsIEnumerable())
            {
                moabTakedown.multiplier *= multiplier;
                __result = true;
            }

            foreach (var eatBloon in model.GetDescendants<EatBloonModel>().AsIEnumerable())
            {
                eatBloon.rbeCashMultiplier *= multiplier;
                __result = true;
            }

            foreach (var wallOfTrees in model.GetDescendants<WallOfTreesModel>().AsIEnumerable())
            {
                wallOfTrees.rbeCashMultiplier *= multiplier;
                __result = true;
            }
        }

        public class CentralMarketDescription : ModTextOverride
        {
            public override string LocalizationKey => $"{UpgradeType.CentralMarket} Description";

            public override bool Active => GetInstance<BetterCentralMarket>().Enabled;

            /*public override string TextValue =>
                "Earns heaps of money each round and increases the end of round income generated by other tower types by 10%.";*/

            public override string TextValue =>
                "Earns heaps of money each round and increases income generated by all non-Support towers by 10%.";
        }
    }
}