using BTD_Mod_Helper.Api.Enums;
using BTD_Mod_Helper.Api.ModOptions;
using BTD_Mod_Helper.Extensions;
using HarmonyLib;
using Il2CppAssets.Scripts.Models;
using Il2CppAssets.Scripts.Models.Towers;
using Il2CppAssets.Scripts.Models.Towers.Behaviors;
using Il2CppAssets.Scripts.Models.Towers.Behaviors.Abilities.Behaviors;
namespace TacticalTweaks.Tweaks;

public class OverlockCash : ToggleableTweak
{
    protected override bool DefaultEnabled => false;

    public override string Description => "Makes the Overclock buff increase end of round cash generated by towers.";

    protected override string Icon => VanillaSprites.MerchantmanUpgradeIcon;

    protected override ModSettingCategory Category => TacticalTweaksMod.Overclock;

    public static void Apply(TowerModel towerModel, float rateModifier)
    {
        foreach (var model in towerModel.GetDescendants<PerRoundCashBonusTowerModel>().AsIEnumerable())
        {
            model.cashPerRound /= rateModifier;
            model.cashRoundBonusMultiplier /= rateModifier;
        }
    }

    [HarmonyPatch(typeof(OverclockModel.OverclockMutator), nameof(OverclockModel.OverclockMutator.Mutate))]
    internal static class OverclockMutator_Mutate
    {
        [HarmonyPostfix]
        internal static void Postfix(OverclockModel.OverclockMutator __instance, Model model)
        {
            if (!GetInstance<OverlockCash>().Enabled || !model.Is(out TowerModel towerModel)) return;

            var rateModifier = __instance.overclockModel.rateModifier;

            Apply(towerModel, rateModifier);
        }
    }

    [HarmonyPatch(typeof(OverclockPermanentModel.OverclockPermanentMutator),
        nameof(OverclockPermanentModel.OverclockPermanentMutator.Mutate))]
    internal static class OverclockPermanentModel_Mutate
    {
        [HarmonyPostfix]
        internal static void Postfix(OverclockPermanentModel.OverclockPermanentMutator __instance, Model model)
        {
            if (!GetInstance<OverlockCash>().Enabled || !model.Is(out TowerModel towerModel)) return;

            var rateModifier = 1 - __instance.stacks * (1 - __instance.overclockPermanentModel.rateModifier);

            Apply(towerModel, rateModifier);
        }
    }
}